name: Deploy to Sakura VPS

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'stg' }}

    env:
      SSH_USERNAME: ${{ vars.SSH_USERNAME }}
      SERVER_HOST: ${{ vars.SERVER_HOST }}
      DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_BASE64 }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts

      - name: Set up Java 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Package artifact
        run: |
          mkdir -p package
          cp build/libs/*SNAPSHOT.jar package/app.jar 
          cp Dockerfile package/

      - name: Deploy via rsync
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./package/ $SSH_USERNAME@$SERVER_HOST:$DEPLOY_PATH

      - name: Restart Docker Container
        run: |
          ENVIRONMENT=${{ github.environment }}
          CONTAINER_NAME="macdogacha-backend-$ENVIRONMENT"
          SHORT_SHA=${GITHUB_SHA::7}

          if [ "$ENVIRONMENT" = "prod" ]; then
            TAG="prod-$SHORT_SHA"
            VPS_PORT=8080
          else
            TAG="stg-$SHORT_SHA"
            VPS_PORT=8081
          fi
          
          echo "Deploying to $ENVIRONMENT environment with tag $TAG"
          
          ssh -T $SSH_USERNAME@$SERVER_HOST << EOF
            set -e
            cd $DEPLOY_PATH
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
          
            docker build -t macdogacha-backend:$TAG .
          
            docker run -d \
              --name $CONTAINER_NAME \
              -p $VPS_PORT:8080 \
              -e SPRING_PROFILES_ACTIVE=$ENVIRONMENT \
              macdogacha-backend:$TAG
          EOF
